cabal-version:      3.14
name:               hs-model-check-demo
version:            0.1.0.0
license:            ISC
author:             Justin Handville
maintainer:         nanolith@gmail.com
build-type:         Simple
extra-doc-files:    README.md

common warnings
    ghc-options: -Wall

executable hs-model-check-demo
    import:           warnings
    main-is:          Main.hs
    build-depends:
          base
        , containers
        , grisette
        , megaparsec
        , parser-combinators
        , sbv < 12.0
        , text
    hs-source-dirs:   .
    other-modules:
          CalculatorDSL
        , CalculatorParser
    default-language: Haskell2010
    default-extensions:
          DeriveGeneric
        , DeriveAnyClass
        , DerivingStrategies
        , DerivingVia
        , FlexibleContexts
        , FlexibleInstances
        , GeneralizedNewtypeDeriving
        , OverloadedStrings
        , StandaloneDeriving
        , TypeApplications
        , TypeFamilies
        , TypeFamilyDependencies
        , UndecidableInstances
